### ISSUE TITLE
support utf-8 charset by default

### ISSUE THREAD

**Issue by apexdodge** [Api2Pdf/api2pdf.java#1]
Reports that using meta charset="UTF-8" in head of html is ignored while using the java client library. Annoying.

This is the reported fix to the makeRequest function:

![image](https://user-images.githubusercontent.com/777005/52968695-fc654500-337b-11e9-8ae7-215408ff059a.png)

**Comment by HusseinMosaad** [comment]
fixed in 1.0.4
