### ISSUE TITLE
Single Quotes vs Double Quotes in /chrome/html endpoint

### ISSUE THREAD

**Issue by corrspt** [Api2Pdf/api2pdf.java#2]
Hi,

I've started using api2pdf via this library and one thing that happened to me was that I was getting a 400 http response from the endpoint, and couldn't find out what was wrong (I was kind of expecting the `error` field in the response to help me out).

I was was calling the following api:
`Api2PdfResponse pdfResponse =
          a2pClient.headlessChromeFromHtml("the html content", false, "file.pdf", options);`

After digging through the source code of the library I saw that you guys build the JSON input for the api as the following:

```java
String payload = "{\"html\":\"" + html + "\",\"inlinePdf\":" + inlinePdf + ",\"fileName\":\"" + fileName
				+ "\", \"options\":{ " + optionsPayload + "}}";
```

Which means that any `double quotes` on the `html` variable would probably mess things up and sure enough, once I changed all double quotes to single quotes, things started working.

One thing that was kind frustrating to find out was that after this I added `<meta charset="utf-8" />` (notice the double quotes) and had weird errors when using things like `º` (displayed as `Aº `). Once I put the single quotes, everything was ok. (This issue with the encoding also happended when using the swagger api documentation)

**Comment by bootleg224** [comment]
Hey @corrspt I believe you may be using an older version of the library, we updated it to use proper serialization: 		String payload = objectMapper.writeValueAsString(model);

https://github.com/Api2Pdf/api2pdf.java/blob/master/api2pdf/src/main/java/com/api2pdf/client/Api2PdfClient.java

Please update your code base and let us know if you have further issues

**Comment by corrspt** [comment]
The README suggests to install version `1.0.1` (the one I'm using). Looking at the releases in github it only shows `1.0`. 

I've tried searching maven (https://mvnrepository.com/artifact/com.api2pdf.client/api2pdf) and it seems there's a 1.0.4, is this the one you want me to update to?

**Comment by corrspt** [comment]
Ok, just an update. Upgrading to 1.0.4 really does fix the issue. thanks. I've seen the README has been updated as well :)
