### ISSUE TITLE
want to convert word file to pdf.

### ISSUE THREAD

**Issue by sravani-gadaputi** [Api2Pdf/api2pdf.java#4]
Here want to pass the Word file blob and need to get  the pdf file.Can you please help me on this.Thanks in advance

**Comment by apexdodge** [comment]
You need to use the libreoffice endpoint but the endpiont does not take raw files. You need to upload it to a server and provide a url to the file. You can upload the file to AWS S3, or Azure Blob, or Google Storage are the most popular storage providers. Make sure the url is publicly accessible.

```
Api2PdfResponse pdfResponse = a2pClient.libreofficeConvert("https://your-url-to-file", true, "test.pdf");
System.out.println(pdfResponse.getPdf());
```
